language: python
python:
  - 3.4
  - 3.5
  - 3.6

before_script:
  - pip install bgmi
  - pip install codecov
  - pip install coverage
  - bgmi install
  - cd ~/.bgmi;
    rm -rf scripts;
    ln -s $TRAVIS_BUILD_DIR scripts;
    cd $TRAVIS_BUILD_DIR;

script:
  - coverage run -a Goblin_Slayer.py
  - coverage run -a Sword_Art_Online_Alicization.py
  - coverage run -a Tensei_Shitara_Slime_Datta_Ken.py
  - coverage run -a Toaru_Majutsu_no_Index.py
  - coverage run -a Tonari_no_Kyuuketsu_San.py

after_success:
  - codecov