language: python
python:
  - 3.4
  - 3.5
  - 3.6

before_script:
  - pip install bgmi
  - pip install codecov
  - pip install coverage
  - bgmi install
  - cd ~/.bgmi;
    rm -rf scripts;
    ln -s $TRAVIS_BUILD_DIR scripts;
    cd $TRAVIS_BUILD_DIR;

script:
  - bash .ci_test.sh

after_success:
  - codecov